/**
 * SRE Notes — Site Data (auto-generated by build.mjs)
 * Single source of truth for categories, articles, tags.
 */
window.SREData = (function() {
  var CATEGORIES = [
{{CATEGORIES}}
  ];

  var ARTICLES = [
{{ARTICLES}}
  ];

  // Compute counts (already included in CATEGORIES at build time)
  // Sort articles by date desc
  ARTICLES.sort(function(a, b) { return b.date.localeCompare(a.date); });

  return {
    categories: CATEGORIES,
    articles: ARTICLES,
    getByCategory: function(catId) {
      return ARTICLES.filter(function(a) { return a.category === catId; });
    },
    getByTag: function(tag) {
      return ARTICLES.filter(function(a) { return (a.tags || []).indexOf(tag) !== -1; });
    },
    getRecent: function(n) {
      return ARTICLES.slice(0, n || 6);
    },
    findByUrl: function(url) {
      for (var i = 0; i < ARTICLES.length; i++) {
        if (ARTICLES[i].url === url) return ARTICLES[i];
      }
      return null;
    }
  };
})();